---
title: 'Lecture 4: Review of Statistics (2)'
author: "Chuxin Liu"
date: "February 15, 2019"
output: 
  beamer_presentation:
    slide_level: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=4, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )
library(tidyverse)
library(hrbrthemes)
```


## Today

- Finish reviewing statistics
- Quiz 3: due tonight, 11:59pm
- Assignment 1: due Feb 24 (Sunday), 11:59pm


## 3.2 Hypothesis Testing Concerning the Population Mean


plot(x=out$time, y=out$S, ylab="fraction", xlab="time", type="l")


# Comparing Means for Different Populations

## Hypothesis tests for difference Between two means

### Step 1: write down null

- Null hypothesis: $H_0: \mu_m-\mu_w = d_0$
- Alternative hypothesis: $H_1: \mu_m-\mu_w \neq d_0$

### What if we want to test if two groups are significantly different in their means?

- Null hypothesis: $H_0: \mu_m-\mu_w = 0$
- Alternative hypothesis: $H_1: \mu_m-\mu_w \neq 0$

## Step 2: construct standard error

- Mean
- Variance
- Standard error

## Step 3: construct t-statistics

T-stat

## Step 4: get p-value

## Step 5: reject or fail to reject

### What do they mean???

- if reject: two groups' mean, $\mu_m$ and $\mu_w$, are significantly different
- if fail to reject: we cannot conclude that two groups have significantly different mean








































# Review Concepts of Chapter 3

## Concepts 3.1-3.3

![]

## Concepts 3.5-3.7

![]


